docker run --rm alpine:3.19 sh -c "apk add --no-cache dovecot-fts && doveadm pw -s SHA512-CRYPT -p 'Director123'"
# Repite para cada cuenta y escribe líneas como:
# director@reprobados.com|{SHA512-CRYPT}$6$...
# admin@reprobados.com|{SHA512-CRYPT}$6$...