FROM nginx:alpine
RUN sed -i 's/# server_tokens off;/server_tokens off;/' /etc/nginx/nginx.conf
RUN apk add --no-cache iputils
COPY web/ /usr/share/nginx/html/
RUN chown -R nginx:nginx /usr/share/nginx/html
USER nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]