FROM postgres:alpine

RUN apk add --no-cache dcron

COPY db/backup.sh /usr/local/bin/backup.sh
RUN chmod +x /usr/local/bin/backup.sh

RUN echo "0 * * * * /usr/local/bin/backup.sh" | crontab -
RUN mkdir -p /backups
VOLUME /backups

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["postgres"]