FROM nginx:alpine

RUN sed -i 's/# server_tokens off;/server_tokens off;/' /etc/nginx/nginx.conf && \
    sed -i 's/# server_tokens off;/server_tokens off;/' /etc/nginx/conf.d/default.conf

RUN apk add --no-cache iputils

COPY web/ /usr/share/nginx/html/
RUN chown -R nginx:nginx /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html

EXPOSE 80
USER nginx
CMD ["nginx", "-g", "daemon off;"]